/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#3b1382",
        "surface": "#eff8ff",
        "secondary": "#705900",
        "on-primary": "#ecf3ff",
        "on-primary-fixed": "#000000",
        "on-primary-container": "#00253f",
        "secondary-dim": "#624d00",
        "on-secondary-container": "#584500",
        "surface-dim": "#c2d7e7",
        "on-background": "#233038",
        "error-container": "#fb5151",
        "inverse-on-surface": "#919fa9",
        "tertiary": "#6747b0",
        "outline": "#6b7982",
        "on-error": "#ffefee",
        "primary-container": "#2ea7ff",
        "surface-container-highest": "#cbe0ee",
        "on-surface": "#233038",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#00a1fe",
        "primary-dim": "#005386",
        "surface-tint": "#005f99",
        "tertiary-fixed-dim": "#b191fe",
        "surface-container": "#d9ebf7",
        "primary-fixed": "#2ea7ff",
        "secondary-fixed": "#fecb00",
        "primary-fixed-dim": "#0099f2",
        "tertiary-dim": "#5b3aa3",
        "error-dim": "#9f0519",
        "outline-variant": "#a1afb9",
        "on-tertiary-fixed-variant": "#44208b",
        "secondary-fixed-dim": "#eebe00",
        "on-tertiary": "#f8f0ff",
        "on-secondary-fixed-variant": "#634e00",
        "background": "#eff8ff",
        "on-error-container": "#570008",
        "surface-variant": "#cbe0ee",
        "inverse-surface": "#031017",
        "on-surface-variant": "#505d66",
        "surface-container-low": "#e3f3ff",
        "tertiary-container": "#bda1ff",
        "on-secondary": "#fff1d5",
        "surface-container-high": "#d2e5f3",
        "primary": "#005f99",
        "surface-bright": "#eff8ff",
        "on-primary-fixed-variant": "#002e4e",
        "on-tertiary-fixed": "#1f0052",
        "on-secondary-fixed": "#413200",
        "tertiary-fixed": "#bda1ff",
        "secondary-container": "#fecb00",
        "error": "#b31b25"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
};
